# -*- coding: utf-8 -*-
"""Object-Detection-on-Video

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qt4WT9MHs93YD1INsGKQtnH3xB_u5-54
"""

pip install imageai

from imageai.Detection import VideoObjectDetection
import os

execution_path = os.getcwd()

print(execution_path)

cd /content/drive/My Drive/Crowd-Counter

detector = VideoObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath( os.path.join(execution_path , "drive/My Drive/Crowd-Counter/resnet50_coco_best_v2.0.1.h5"))
detector.loadModel()

def forFrame(frame_number, output_array, output_count):
    print("FOR FRAME " , frame_number)
    print("Output for each object : ", output_array)
    print("Output count for unique objects : ", output_count)
    print("------------END OF A FRAME --------------")

def forSeconds(second_number, output_arrays, count_arrays, average_output_count):
    print("SECOND : ", second_number)
    print("Array for the outputs of each frame ", output_arrays)
    print("Array for output count for unique objects in each frame : ", count_arrays)
    print("Output average count for unique objects in the last second: ", average_output_count)
    print("------------END OF A SECOND --------------")

def forMinute(minute_number, output_arrays, count_arrays, average_output_count):
    print("MINUTE : ", minute_number)
    print("Array for the outputs of each frame ", output_arrays)
    print("Array for output count for unique objects in each frame : ", count_arrays)
    print("Output average count for unique objects in the last minute: ", average_output_count)
    print("------------END OF A MINUTE --------------")

video_detector = VideoObjectDetection()
video_detector.setModelTypeAsRetinaNet()
video_detector.setModelPath(os.path.join(execution_path, "drive/My Drive/Crowd-Counter/resnet50_coco_best_v2.0.1.h5"))
video_detector.loadModel()

video_detector.detectObjectsFromVideo(
    input_file_path=os.path.join(execution_path, "drive/My Drive/Crowd-Counter/Antalya_Eski_Lara.mp4"),
    output_file_path=os.path.join(execution_path, "drive/My Drive/Crowd-Counter/Antalya_Eski_Lara_Detected"),
    frames_per_second=10,
    per_second_function=forSeconds,
    per_frame_function=forFrame,
    per_minute_function=forMinute,
    minimum_percentage_probability=30
)